
GET {{apiUrl}}/issueBook/getAll HTTP/1.1
authorization: {{token}}

###

###
// Return a book
PUT {{apiUrl}}/issueBook/returnBook
authorization: {{token}}
content-type: {{content-type}}

{
   "id" : "60df30c0201c5c20642378ea" 
}

###
GET {{apiUrl}}/issueBook/getById/60df30c0201c5c20642378ea
authorization: {{token}}


###

POST {{apiUrl}}/issueBook HTTP/1.1
authorization: {{token}}
content-type: {{content-type}}

{
  "bookId" : "60d1f910e648ce50f070cddf",
  "studentId" : "60df2d90cd9e2d1e30ef42d8"
}
