
GET http://localhost:9001/api/authors/getAll HTTP/1.1
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MGNjOWYyYTM4YTA2MDVhZTc5YjQxZDgiLCJuYW1lIjoiQWRpdHlhIEFkaGlrYXJpIiwidXNlcm5hbWUiOiJmcm9udF9kZXNrIiwiX192IjowLCJpYXQiOjE2MjQ3OTk1NDIsImV4cCI6MTYyNDg4NTk0Mn0.x8Culz-luCReG7m8VmGlCrd-EL819K6vSV0MPGiHzig

###

POST http://localhost:9001/api/authors HTTP/1.1
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MGNjOWYyYTM4YTA2MDVhZTc5YjQxZDgiLCJuYW1lIjoiQWRpdHlhIEFkaGlrYXJpIiwidXNlcm5hbWUiOiJmcm9udF9kZXNrIiwiX192IjowLCJpYXQiOjE2MjQ3OTk1NDIsImV4cCI6MTYyNDg4NTk0Mn0.x8Culz-luCReG7m8VmGlCrd-EL819K6vSV0MPGiHzig
content-type: application/json

{
  "name": "Shakes "
}


