GET http://localhost:9001/api/books/getAll HTTP/1.1
Auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MGNjOWYyYTM4YTA2MDVhZTc5YjQxZDgiLCJuYW1lIjoiQWRpdHlhIEFkaGlrYXJpIiwidXNlcm5hbWUiOiJmcm9udF9kZXNrIiwiX192IjowLCJpYXQiOjE2MjQzNjg5MzksImV4cCI6MTYyNDM2OTAzOX0.rXKihE9JwZ0qMTwq373roXs3RT5VsWN8a14KZbK8z7M
###

POST http://localhost:9001/api/books HTTP/1.1
{
  "name": "Javascript",
  "price": 1000,
}
