
GET http://localhost:9001/api/books/getAll HTTP/1.1
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MGNjOWYyYTM4YTA2MDVhZTc5YjQxZDgiLCJuYW1lIjoiQWRpdHlhIEFkaGlrYXJpIiwidXNlcm5hbWUiOiJmcm9udF9kZXNrIiwiX192IjowLCJpYXQiOjE2MjQ1MTMwMDEsImV4cCI6MTYyNDU5OTQwMX0.9NkJDSKlPsDqFNhrcxN-_7QbLmnUhgY95hjH9hcs_Q0

###

POST http://localhost:9001/api/books HTTP/1.1
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MGNjOWYyYTM4YTA2MDVhZTc5YjQxZDgiLCJuYW1lIjoiQWRpdHlhIEFkaGlrYXJpIiwidXNlcm5hbWUiOiJmcm9udF9kZXNrIiwiX192IjowLCJpYXQiOjE2MjQ3OTk1NDIsImV4cCI6MTYyNDg4NTk0Mn0.x8Culz-luCReG7m8VmGlCrd-EL819K6vSV0MPGiHzig
content-type: application/json

{
  "name": "Jana TT",
  "price": 1000,
  "author_id" : "60d87f74d3a48bc699dfd2fd"
}

###

GET http://localhost:9001/api/books/getWithAuthors HTTP/1.1
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MGNjOWYyYTM4YTA2MDVhZTc5YjQxZDgiLCJuYW1lIjoiQWRpdHlhIEFkaGlrYXJpIiwidXNlcm5hbWUiOiJmcm9udF9kZXNrIiwiX192IjowLCJpYXQiOjE2MjQ3OTk1NDIsImV4cCI6MTYyNDg4NTk0Mn0.x8Culz-luCReG7m8VmGlCrd-EL819K6vSV0MPGiHzig
content-type: application/json